// A trusted whiteboard document hosted inside the tab workspace.
(()=>{if(window.parent===window||new URLSearchParams(location.search).get('pane')!=='1')return;
document.documentElement.classList.add('embedded-pane');const style=document.createElement('style');style.textContent='.embedded-pane body>header{display:none!important}.embedded-pane main{height:100dvh!important}.embedded-pane #workspaceSidebar{top:0!important}.embedded-pane #windowWorkspace{display:none!important}.embedded-pane #canvasTools{bottom:18px}.embedded-pane #hint{display:none}.embedded-pane #textSizeTools{left:12px;transform:none;right:12px;width:max-content;max-width:calc(100% - 24px)}';document.head.append(style);$('workspaceSidebar').hidden=true;
const send=(type,extra={})=>parent.postMessage({type,...extra},location.origin);let reporting=false,visible=true;
function state(){return {boardId:typeof boardId==='string'?boardId:'',name:board?.name||'',dirty:!!dirty,blocked:!!blocked,saving:!!savePromise,loading:!!loading}}
function report(){if(reporting)return;reporting=true;queueMicrotask(()=>{reporting=false;send('pane-state',{state:state()})})}
const beforeLoad=loadBoard;loadBoard=async function(id){if(board&&boardId&&id!==boardId){$('boards').value=boardId;send('pane-open',{boardId:id});return}await beforeLoad(id);report()};
const beforeChange=change;change=function(){beforeChange();report()};const beforePersist=persist;persist=async function(){try{return await beforePersist()}finally{report()}};
function pauseMedia(doc=document){for(const media of doc.querySelectorAll('audio,video'))media.pause();for(const f of doc.querySelectorAll('iframe'))try{if(f.contentDocument)pauseMedia(f.contentDocument)}catch{}}
window.whiteboardPane={state,flush:()=>persist(),focus:()=>{if($('dialog').open)return;const active=document.activeElement;if(active?.closest('.live-layout')&&active.matches('input,textarea,[contenteditable=true]')&&!active.readOnly){active.focus({preventScroll:true});return}canvas.tabIndex=-1;canvas.focus({preventScroll:true})},setVisible:next=>{if(visible&&!next){captureReading();pauseMedia();persist().catch(()=>{})}visible=next},command:async name=>{if(name==='library')await showWorkspaceTab('assetPane');else if(name==='boards')await showWorkspaceTab('manager');else if(name==='ai')$('aiWorkspace').click();else if(name==='help')wfHelp();else if(name==='settings')interfaceSettings();else if(name==='search')wfOpenSearch();else if(name==='recovery')await wfRecovery();else if(name==='rename')$('rename').click();else if(name==='group')groupSelection();else if(name==='export')exportJSON();else if(name==='markdown')exportMarkdown()}};
let canvasWidth=0,canvasHeight=0,resizeSave;
const canvasSize=new ResizeObserver(entries=>{const {width,height}=entries[0].contentRect;if(width<1||height<1)return;if(board&&canvasWidth&&canvasHeight){view().x+=(width-canvasWidth)/2;view().y+=(height-canvasHeight)/2;moveView();clearTimeout(resizeSave);resizeSave=setTimeout(()=>{if(board&&!loading){change()}},200)}canvasWidth=width;canvasHeight=height});canvasSize.observe(canvas);
document.addEventListener('pointerdown',()=>send('pane-active'),true);document.addEventListener('keydown',e=>{send('pane-active');if((e.ctrlKey||e.metaKey)&&e.key==='Tab'){e.preventDefault();e.stopImmediatePropagation();send('pane-shortcut',{reverse:e.shiftKey})}},true);
if($('windowWorkspace'))$('windowWorkspace').onclick=()=>send('pane-split');
window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.type==='pane-focus')window.whiteboardPane.focus()});
const originalHelp=wfHelp;wfHelp=function(){originalHelp();const body=$('dialogBody');const note=document.createElement('p');note.textContent='当前工作区使用标签页：点击上方标签切换；“左右分栏”可并排显示。拖动分隔线调整比例，双击恢复各半。标签右键可以移到另一侧。';body.prepend(note)};
if(board)report();
})();
