// Reading, placement and table sizing use the same rules in every document.
(() => {
 'use strict';
 const fieldMeasurements=new WeakMap();
 growContentFields=function(root=document){const changed=[];for(const field of root.querySelectorAll('.node textarea')){const style=getComputedStyle(field),signature=[field.value,field.offsetWidth,style.fontSize,style.lineHeight,style.paddingLeft,style.paddingRight].join('|');field.classList.toggle('empty-field',!field.value.trim());if(fieldMeasurements.get(field)===signature)continue;fieldMeasurements.set(field,signature);changed.push(field)}for(const field of changed)field.style.height='0px';const heights=changed.map(field=>Math.max(field.scrollHeight+2,field.matches('[data-row]')?40:28));changed.forEach((field,i)=>field.style.height=heights[i]+'px')};
 interfaceSettings=()=>whiteboardAppearance.open();
 canvas.addEventListener('click',e=>{const action=e.target.closest('.table-options button');if(action)action.closest('details').open=false});
 function readNote(id){const n=board.nodes.find(n=>n.id===id);if(!n)return;if(n.assetId)return previewAsset(n.assetId);if(n.type==='table'){openEditor(id);return}showDialog('<article class="reading-sheet"><h3>'+esc(n.title||'未命名内容')+'</h3>'+[['',n.body],['自己的补充',n.userText],['备注',n.annotation]].filter(([_,text])=>text).map(([label,text])=>'<section>'+(label?'<small>'+label+'</small>':'')+esc(text)+'</section>').join('')+'</article>',[['返回白板',()=>$('dialog').close()],['在白板编辑',()=>{$('dialog').close();openEditor(id);$('body')?.focus()}]]);$('dialog').classList.add('reading-dialog');$('dialog').addEventListener('close',()=>$('dialog').classList.remove('reading-dialog'),{once:true})}
 const originalMount=whiteboardExperience.fitBlock;
 function mount(){const byId=new Map(board?.nodes.map(n=>[n.id,n])||[]);for(const el of $('nodes').children){const n=byId.get(el.dataset.id);if(!n)continue;const actions=el.querySelector('.block-actions');if(actions&&!actions.querySelector('.block-read')&&!n.assetId&&n.type!=='table'){const b=document.createElement('button');b.className='block-read';b.title='展开阅读';b.setAttribute('aria-label','展开阅读');b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 9V4h5m6 0h5v5M4 15v5h5m6 0h5v-5"/></svg>';b.onclick=e=>{e.stopPropagation();readNote(n.id)};actions.prepend(b)}const drag=actions?.querySelector('.block-transfer');if(drag){drag.title='复制到表格、内容库或另一张白板';drag.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/></svg>'}
  for(const handle of el.querySelectorAll('.table-column-resize'))bindWidth(handle,n);
 }}
 const draw=drawNodes;drawNodes=function(){draw();mount()};const select=refreshSelectionUI;refreshSelectionUI=function(){select();mount()};
 const layout=tableLayout;tableLayout=function(n){const widths=n.columns.map((_,i)=>Math.max(100,Math.min(900,n.columnWidths?.[i]||160))),width=38+widths.reduce((a,b)=>a+b,0);const explicit=n.columnWidths?.length===n.columns.length;return layout(n).replace(/style="min-width:[^"]+"/,'style="min-width:'+(explicit?width:38+n.columns.length*140)+'px;width:'+(explicit?width+'px':'100%')+'"').replace('<thead>','<colgroup><col style="width:38px">'+widths.map(w=>explicit?'<col style="width:'+w+'px">':'<col>').join('')+'</colgroup><thead>').replace(/(<th data-col-target="(\d+)"[^>]*>)/g,'$1<span class="table-column-resize inline-ui" data-width-column="$2" aria-label="调整列宽"></span>')};
 function bindWidth(handle,n){if(handle.dataset.bound)return;handle.dataset.bound='true';let start=null;handle.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();undoPoint();const heads=[...handle.closest('table').querySelectorAll('thead th[data-col-target]')];n.columnWidths=n.columns.map((_,i)=>n.columnWidths?.[i]||heads[i].offsetWidth);start={x:e.clientX,width:n.columnWidths[+handle.dataset.widthColumn],z:view().z};handle.setPointerCapture(e.pointerId);handle.classList.add('resizing')};handle.onpointermove=e=>{if(!start)return;e.preventDefault();const i=+handle.dataset.widthColumn;n.columnWidths[i]=Math.max(100,Math.min(900,start.width+(e.clientX-start.x)/start.z));const table=handle.closest('table'),width=38+n.columnWidths.reduce((a,b)=>a+b,0);table.querySelectorAll('col')[i+1].style.width=n.columnWidths[i]+'px';table.style.width=table.style.minWidth=width+'px';growContentFields(table)};const end=()=>{if(!start)return;start=null;handle.classList.remove('resizing');change()};handle.onpointerup=end;handle.onpointercancel=end;handle.onlostpointercapture=end;handle.ondblclick=e=>{e.stopPropagation();undoPoint();n.columnWidths=n.columns.map((_,i)=>i===+handle.dataset.widthColumn?160:n.columnWidths?.[i]||160);drawNodes();change()}}
 const move=moveTable;moveTable=function(n,axis,from,to){const widths=clone(n.columnWidths||[]);move(n,axis,from,to);if(axis==='column'&&widths.length===n.columns.length&&from!==to){widths.splice(to,0,widths.splice(from,1)[0]);n.columnWidths=widths;drawNodes();change()}};
 for(const field of ['columnWidths'])if(!wfContentFields.includes(field))wfContentFields.push(field);
 wfLabels.columnWidths='表格列宽';
 const preview=document.createElement('div');preview.className='board-drop-preview';preview.hidden=true;preview.innerHTML='<span>复制到这里</span>';canvas.append(preview);
 canvas.addEventListener('dragover',e=>{if(![...e.dataTransfer.types].some(t=>['application/x-creative-board-content','application/x-creative-assets'].includes(t))||e.target.closest('[data-cell]')){preview.hidden=true;return}const r=canvas.getBoundingClientRect();preview.hidden=false;preview.style.left=(e.clientX-r.left)+'px';preview.style.top=(e.clientY-r.top)+'px';e.dataTransfer.dropEffect='copy'},true);
 for(const name of ['drop','dragend','dragleave'])canvas.addEventListener(name,e=>{if(name!=='dragleave'||!canvas.contains(e.relatedTarget))preview.hidden=true},true);
 window.addEventListener('dragend',()=>preview.hidden=true);
 window.whiteboardReading={open:readNote};
 if(board)mount();
})();
