'use strict';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),frames=new Map();
let boards=[],model={tabs:[],active:{left:null,right:null},side:'left',split:false,ratio:50},pickerSide='left',contextTab=null,dragTab=null,toastTimer;
function toast(text){$('shellToast').textContent=text;$('shellToast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('shellToast').hidden=true,4500)}
async function api(path,options){const r=await fetch(path,options);if(!r.ok){let value;try{value=await r.json()}catch{}throw Error(value?.error||'读取失败，请稍后再试')}return r.json()}
function saveLayout(){const value=JSON.stringify(model);try{sessionStorage.setItem('creative-board-tabs',value);localStorage.setItem('creative-board-tabs-last',value)}catch{toast('浏览器未能记住布局；白板内容仍单独保存')}}
function pane(tab){try{return frames.get(tab?.id)?.contentWindow.whiteboardPane}catch{return null}}
function current(side=model.side){return model.tabs.find(t=>t.id===model.active[side])}
function normalizeLayout(){for(const side of ['left','right'])if(!model.tabs.some(t=>t.id===model.active[side]&&t.side===side))model.active[side]=model.tabs.find(t=>t.side===side)?.id||null;if(!model.split){for(const t of model.tabs)t.side='left';model.active.left=model.active.left||model.active.right||model.tabs[0]?.id||null;model.active.right=null;model.side='left'}model.ratio=Math.max(20,Math.min(80,Number(model.ratio)||50))}
function updateStatus(){const t=current(),s=pane(t)?.state();$('shellStatus').textContent=s?.blocked?'有冲突 · 修改已保留':s?.dirty?'正在保存…':(s?.loading||t&&!s)?'正在打开…':t?'已保存':'选择一张白板';document.title=t?(t.name+' · 创作白板'):'创作白板';for(const button of document.querySelectorAll('#shellHeader [data-command]'))button.disabled=!t}
function renderTabs(){normalizeLayout();$('workspace').classList.toggle('is-split',model.split);$('workspace').style.setProperty('--split',model.ratio+'%');$('splitToggle').setAttribute('aria-pressed',String(model.split));$('splitToggle').textContent=model.split?'合并分栏':'左右分栏';$('splitter').setAttribute('aria-valuenow',String(Math.round(model.ratio)));
for(const side of ['left','right']){const group=document.querySelector('.tab-group[data-side='+side+']'),list=group.querySelector('.tabs'),scroll=list.scrollLeft;group.classList.toggle('active-pane',model.side===side);list.replaceChildren();for(const t of model.tabs.filter(t=>t.side===side)){const item=document.createElement('div');item.className='tab';item.dataset.tab=t.id;item.draggable=true;item.setAttribute('aria-current',String(model.active[side]===t.id));const open=document.createElement('button');open.className='tab-open';open.setAttribute('role','tab');open.setAttribute('aria-selected',String(model.active[side]===t.id));open.title=t.name;open.textContent=t.name;open.onclick=()=>activate(t.id);const state=document.createElement('span');state.className='state';const status=pane(t)?.state();state.textContent=status?.blocked?'!':status?.dirty?'●':'';state.title=status?.blocked?'存在修改冲突':status?.dirty?'尚未保存':'';const close=document.createElement('button');close.className='tab-close';close.textContent='×';close.setAttribute('aria-label','关闭标签：'+t.name);close.onclick=()=>closeTab(t.id);item.append(open,state,close);item.oncontextmenu=e=>{e.preventDefault();contextTab=t.id;$('tabContext').hidden=false;$('tabContext').style.left=Math.min(e.clientX,innerWidth-170)+'px';$('tabContext').style.top=Math.min(e.clientY,innerHeight-100)+'px'};item.ondragstart=e=>{dragTab=t.id;e.dataTransfer.setData('application/x-creative-tab',t.id);e.dataTransfer.effectAllowed='move';$('workspace').classList.add('tab-dragging')};item.ondragend=()=>{dragTab=null;$('workspace').classList.remove('tab-dragging')};item.ondragover=e=>{if(dragTab)e.preventDefault()};item.ondrop=e=>{e.preventDefault();e.stopPropagation();moveTab(dragTab,side,t.id)};list.append(item)}list.scrollLeft=scroll}
for(const t of model.tabs){const visible=(t.side==='left'||model.split)&&model.active[t.side]===t.id;if(visible&&!frames.has(t.id))createFrame(t);const frame=frames.get(t.id);if(!frame)continue;frame.hidden=!visible;frame.style.left=t.side==='right'?model.ratio+'%':'0';frame.style.width=!model.split?'100%':t.side==='left'?model.ratio+'%':(100-model.ratio)+'%';frame.setAttribute('aria-hidden',String(!visible));pane(t)?.setVisible(visible)}
for(const side of ['left','right'])document.querySelector('.empty-pane[data-side='+side+']').hidden=!!current(side);updateStatus();saveLayout()}
function createFrame(t){const f=document.createElement('iframe');f.className='board-frame';f.dataset.tabId=t.id;f.title=t.name;f.hidden=true;frames.set(t.id,f);f.src='/index.html?pane=1&board='+encodeURIComponent(t.boardId)+'&tabId='+t.id;f.onload=()=>{renderTabs();if(current()?.id===t.id)pane(t)?.focus()};$('frameDeck').append(f)}
function openBoard(id,side=model.side){const b=boards.find(b=>b.id===id);if(!b){toast('这张白板已经不存在，请重新选择');return}const existing=model.tabs.find(t=>t.boardId===id);if(existing){if(existing.side!==side)moveTab(existing.id,side);else activate(existing.id);return}if(side==='right')model.split=true;const t={id:uid(),boardId:id,name:b.name,side};model.tabs.push(t);model.active[side]=t.id;model.side=side;createFrame(t);renderTabs()}
function activate(id){const t=model.tabs.find(t=>t.id===id);if(!t)return;const old=current();if(old&&old.id!==id)pane(old)?.flush().catch(()=>{});model.side=t.side;model.active[t.side]=id;renderTabs();pane(t)?.focus();document.querySelector('.tab[data-tab="'+id+'"]')?.scrollIntoView({block:'nearest',inline:'nearest'})}
async function closeTab(id){const t=model.tabs.find(t=>t.id===id);if(!t)return;const view=pane(t);try{if(view&&!await view.flush()){activate(id);toast('这张白板还有未保存的修改。请先另存或处理冲突，再关闭标签。');return}}catch(e){toast(e.message);return}frames.get(id)?.remove();frames.delete(id);const index=model.tabs.indexOf(t);model.tabs.splice(index,1);if(model.active[t.side]===id){const next=model.tabs.slice(0,index).reverse().find(n=>n.side===t.side)||model.tabs.find(n=>n.side===t.side);model.active[t.side]=next?.id||null}renderTabs();pane(current())?.focus()}
function moveTab(id,side,before){const t=model.tabs.find(t=>t.id===id);if(!t)return;const old=t.side;if(side==='right')model.split=true;if(before&&before!==id){model.tabs=model.tabs.filter(n=>n.id!==id);model.tabs.splice(Math.max(0,model.tabs.findIndex(n=>n.id===before)),0,t)}t.side=side;if(old!==side&&model.active[old]===id)model.active[old]=model.tabs.find(n=>n.side===old)?.id||null;model.active[side]=id;model.side=side;dragTab=null;$('workspace').classList.remove('tab-dragging');renderTabs();pane(t)?.focus()}
function toggleSplit(){if(model.split){const keep=current()?.id;for(const t of model.tabs)t.side='left';model.split=false;model.active.left=keep||model.active.left;model.side='left'}else{model.split=true;const active=current();if(model.tabs.filter(t=>t.side==='left').length>1&&active){moveTab(active.id,'right');return}}renderTabs()}
async function picker(side=model.side){pickerSide=side;try{boards=await api('/api/boards')}catch(e){toast(e.message);return}$('boardQuery').value='';$('newBoardName').value='';$('pickerHint').textContent='在'+(side==='right'?'右':'左')+'侧打开；已打开的白板会使用原标签。';drawChoices();$('boardPicker').showModal();$('boardQuery').focus()}
function drawChoices(){const list=$('boardChoices');list.replaceChildren();const q=$('boardQuery').value.trim().toLowerCase();for(const b of boards.filter(b=>b.name.toLowerCase().includes(q))){const btn=document.createElement('button'),name=document.createElement('span'),meta=document.createElement('small');name.textContent=b.name;meta.textContent=model.tabs.some(t=>t.boardId===b.id)?'已打开':b.count+' 块内容';btn.append(name,meta);btn.onclick=()=>{$('boardPicker').close();openBoard(b.id,pickerSide)};list.append(btn)}if(!list.children.length)list.textContent='没有找到，可以新建一张白板。'}
async function createBoard(name,side,folder=""){const id=uid(),data={format:'creative-board',version:1,name:name||'未命名白板',folder,nodes:[],edges:[],view:{x:80,y:80,z:1}};await api('/api/boards/'+id,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':'new'},body:JSON.stringify(data)});boards.push({id,name:data.name,count:0});openBoard(id,side);return id}
async function command(name){const t=current(),view=pane(t);if(!view)return toast('白板还在打开，请稍等');$('shellMore').open=false;try{await view.command(name)}catch(e){toast(e.message)}}
function stepTab(offset){const tabs=model.tabs.filter(t=>t.side===model.side);if(!tabs.length)return;const index=tabs.findIndex(t=>t.id===model.active[model.side]);activate(tabs[(index+offset+tabs.length)%tabs.length].id)}
window.addEventListener('message',async e=>{if(e.origin!==location.origin)return;const tab=model.tabs.find(t=>frames.get(t.id)?.contentWindow===e.source);if(!tab)return;const d=e.data;if(d?.type==='pane-state'){if(d.state?.boardId===tab.boardId){tab.name=d.state.name||tab.name;renderTabs()}}else if(d?.type==='pane-active'){$('shellMore').open=false;$('tabContext').hidden=true;if(model.active[tab.side]===tab.id){model.side=tab.side;document.querySelectorAll('.tab-group').forEach(el=>el.classList.toggle('active-pane',el.dataset.side===tab.side));updateStatus();saveLayout()}}else if(d?.type==='pane-open'){try{boards=await api('/api/boards');openBoard(d.boardId,tab.side)}catch(err){toast(err.message)}}else if(d?.type==='pane-shortcut'){model.side=tab.side;stepTab(d.reverse?-1:1)}else if(d?.type==='pane-split'){model.side=tab.side;toggleSplit()}else if(d?.type==='pane-picker')picker(tab.side)});
$('openBoards').onclick=()=>current()?command('sidebar'):picker();$('boardQuery').oninput=drawChoices;document.querySelectorAll('.add-tab,.choose-board').forEach(b=>b.onclick=()=>picker(b.dataset.side));$('createBoard').onclick=async()=>{try{await createBoard($('newBoardName').value.trim(),pickerSide);$('boardPicker').close()}catch(e){toast(e.message)}};$('newBoardName').onkeydown=e=>{if(e.key==='Enter'){$('createBoard').click();e.preventDefault()}};$('splitToggle').onclick=toggleSplit;
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>command(b.dataset.command));document.querySelectorAll('[data-tab-action]').forEach(b=>b.onclick=()=>{const id=contextTab;$('tabContext').hidden=true;if(b.dataset.tabAction==='close')closeTab(id);else{const t=model.tabs.find(t=>t.id===id);if(t)moveTab(id,t.side==='left'?'right':'left')}});document.addEventListener('pointerdown',e=>{if(!e.target.closest('#shellMore'))$('shellMore').open=false;if(!e.target.closest('#tabContext'))$('tabContext').hidden=true});
document.querySelectorAll('.tab-group').forEach(el=>{el.addEventListener('dragover',e=>{if(dragTab)e.preventDefault()});el.addEventListener('drop',e=>{if(dragTab){e.preventDefault();moveTab(dragTab,el.dataset.side)}});el.addEventListener('pointerdown',()=>{model.side=el.dataset.side;updateStatus()})});$('rightDropTarget').ondragover=e=>e.preventDefault();$('rightDropTarget').ondrop=e=>{e.preventDefault();moveTab(dragTab,'right')};
let resizing=false;const divider=$('splitter');divider.onpointerdown=e=>{if(e.button!==0)return;resizing=true;e.preventDefault();divider.setPointerCapture(e.pointerId);$('workspace').classList.add('resizing')};divider.onpointermove=e=>{if(!resizing)return;const r=$('workspace').getBoundingClientRect();model.ratio=Math.max(20,Math.min(80,(e.clientX-r.left)/r.width*100));renderTabs()};const endResize=()=>{resizing=false;$('workspace').classList.remove('resizing');saveLayout()};divider.onpointerup=endResize;divider.onpointercancel=endResize;divider.onlostpointercapture=endResize;divider.ondblclick=()=>{model.ratio=50;renderTabs()};divider.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home'].includes(e.key))return;e.preventDefault();model.ratio=e.key==='Home'?50:model.ratio+(e.key==='ArrowLeft'?-2:2);renderTabs()};
$('externalWindow').onclick=async()=>{const t=current();if(!t)return;const w=window.open('about:blank','_blank','popup,width=1200,height=850');if(!w)return toast('请允许本站打开新窗口');try{if(!await pane(t).flush()){w.close();return toast('请先处理未保存修改')}w.location.replace('/?board='+encodeURIComponent(t.boardId));$('shellMore').open=false}catch(e){w.close();toast(e.message)}};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('shellMore').open=false;$('tabContext').hidden=true;return}if((e.ctrlKey||e.metaKey)&&e.key==='Tab'){e.preventDefault();stepTab(e.shiftKey?-1:1)}});window.addEventListener('beforeunload',e=>{if(model.tabs.some(t=>{const s=pane(t)?.state();return s?.dirty||s?.saving})){e.preventDefault();e.returnValue=''}});
(async()=>{try{boards=await api('/api/boards');const requested=new URLSearchParams(location.search).get('board');let saved;try{saved=JSON.parse(sessionStorage.getItem('creative-board-tabs')||localStorage.getItem('creative-board-tabs-last')||'null')}catch{}if(requested&&boards.some(b=>b.id===requested)){openBoard(requested,'left')}else if(saved&&Array.isArray(saved.tabs)){model={...model,...saved,tabs:saved.tabs.filter(t=>boards.some(b=>b.id===t.boardId)).map(t=>({...t,side:t.side==='right'?'right':'left',name:boards.find(b=>b.id===t.boardId).name})),active:saved.active||{left:null,right:null}};const seen=new Set();model.tabs=model.tabs.filter(t=>{if(seen.has(t.boardId))return false;seen.add(t.boardId);return true});normalizeLayout();renderTabs()}else if(boards.length){const last=localStorage.getItem('creative-board-last');openBoard(boards.some(b=>b.id===last)?last:boards[0].id,'left')}else await createBoard('我的白板','left')}catch(e){toast(e.message);renderTabs()}})();

window.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey)e.preventDefault()},{passive:false});
