// One explorer for the whole window; the canvas remains responsible for editing.
(() => {
 let open=false,panel='manager',explorerFrame=null,outlineTimer,libraryIds=[],folder='',drag=false,dragWidth=null,sizeFrame=0,lastOutlineKey='';
 try{const p=JSON.parse(localStorage.getItem('creative-sidebar-state')||'{}');open=!!p.open;panel=['manager','assetPane','outline'].includes(p.tab)?p.tab:'manager'}catch{}
 const host=$('globalExplorer'),work=$('workspace');
 const explorer=()=>explorerFrame?.contentWindow.whiteboardExplorer;
 function sizing(){let p;try{p=JSON.parse(localStorage.getItem('creative-interface')||'{}')}catch{p={}}const width=Math.min(innerWidth*.45,Math.max(260,Math.min(520,dragWidth??p.width??340)));work.style.setProperty('--explorer-width',open?width+'px':'0px');work.style.setProperty('--split-number',model.ratio/100);$('shellHeader').style.zoom=p.scale||1;work.style.height=(innerHeight-$('shellHeader').getBoundingClientRect().height)+'px';host.hidden=!open;$('openBoards').setAttribute('aria-expanded',String(open))}
 function ensure(){if(explorerFrame)return;explorerFrame=document.createElement('iframe');explorerFrame.id='explorerFrame';explorerFrame.title='内容与白板';explorerFrame.src='/index.html?pane=1&explorer=1';explorerFrame.onload=()=>{lastOutlineKey='';explorer()?.show(panel);sync();updateStatus()};host.prepend(explorerFrame)}
 function sync(){clearTimeout(outlineTimer);outlineTimer=setTimeout(()=>{if(!open||drag||resizing||!explorer())return;const view=pane(current()),state=view?.state();if(!state){if(!current()){lastOutlineKey='';explorer().setBoard(null)}return}const key=JSON.stringify([state.boardId,state.name,state.revision,panel,panel==='outline'?view.selection():null]);if(key===lastOutlineKey)return;lastOutlineKey=key;explorer().setBoard(view.snapshot())},60)}
 function toggle(nextPanel){if(nextPanel){panel=nextPanel;open=true}else open=!open;if(open){ensure();explorer()?.show(panel);sync()}sizing();localStorage.setItem('creative-sidebar-state',JSON.stringify({open,tab:panel}));if(!open)pane(current())?.focus()}
 const beforeRender=renderTabs;renderTabs=function(){beforeRender();const b=$('splitToggle');b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16"/></svg>';b.title=model.split?'合并分栏':'左右分栏';b.setAttribute('aria-label',b.title);sizing();if(open||!current())ensure();sync()};
 $('openBoards').onclick=()=>toggle();
 const beforeCommand=command;command=async function(name){if(name==='settings'){$('shellMore').open=false;return whiteboardAppearance.open()}if(name==='sidebar')return toggle();if(name==='ai'){const selection=open?explorer()?.selection():null;const target=pane(current())||explorer();if(!current())toggle(panel);return target?.command('ai',{libraryIds:selection?.ids||[],scope:selection?.panel==='assetPane'&&selection.ids.length?'library':null})}if(!current()&&['help','search','recovery'].includes(name)){toggle(panel);return explorer()?.command(name)}return beforeCommand(name)};
 window.addEventListener('message',async e=>{if(e.origin!==location.origin)return;const d=e.data;if(e.source===explorerFrame?.contentWindow){try{if(d?.type==='explorer-catalog'){for(const t of model.tabs)pane(t)?.refreshLibrary()?.catch(err=>toast(err.message))}else if(d?.type==='explorer-dialog')explorerFrame.classList.toggle('explorer-modal',d.open);else if(d?.type==='explorer-toggle')toggle();else if(d?.type==='explorer-panel'){panel=d.panel;localStorage.setItem('creative-sidebar-state',JSON.stringify({open,tab:panel}));sync()}else if(d?.type==='explorer-shortcut')stepTab(d.reverse?-1:1);else if(d?.type==='explorer-selection'){libraryIds=d.ids;folder=d.folder;updateStatus()}else if(d?.type==='explorer-open'){boards=await api('/api/boards');openBoard(d.boardId)}else if(d?.type==='explorer-create'){await createBoard(d.name,model.side,d.folder||'');await explorer()?.refresh()}else if(d?.type==='explorer-place')await pane(current())?.insertLibrary(d.items);else if(d?.type==='explorer-focus'){pane(current())?.focusNode(d.nodeId);pane(current())?.focus()}else if(d?.type==='explorer-command')await pane(current())?.command(d.command,{folder})}catch(err){toast(err.message)}return}const tab=model.tabs.find(t=>frames.get(t.id)?.contentWindow===e.source);if(!tab)return;if(d?.type==='pane-sidebar'){if(d.panel)toggle(d.panel);else toggle()}else if(['pane-state','pane-active'].includes(d?.type))sync()});
 $('splitter').onpointermove=e=>{if(!resizing)return;const r=$('frameDeck').getBoundingClientRect();model.ratio=Math.max(20,Math.min(80,(e.clientX-r.left)/r.width*100));renderTabs()};
 const grip=document.createElement('div');grip.id='explorerGrip';grip.setAttribute('role','separator');grip.setAttribute('aria-label','调整侧栏宽度');host.append(grip);
 grip.onpointerdown=e=>{if(e.button!==0)return;drag=true;dragWidth=host.getBoundingClientRect().width;grip.setPointerCapture(e.pointerId);work.classList.add('explorer-resizing');e.preventDefault()};grip.onpointermove=e=>{if(!drag)return;dragWidth=Math.max(260,Math.min(520,e.clientX));if(!sizeFrame)sizeFrame=requestAnimationFrame(()=>{sizeFrame=0;sizing()})};const stop=()=>{if(!drag)return;drag=false;cancelAnimationFrame(sizeFrame);sizeFrame=0;let p;try{p=JSON.parse(localStorage.getItem('creative-interface')||'{}')}catch{p={}}p.width=dragWidth;localStorage.setItem('creative-interface',JSON.stringify(p));dragWidth=null;work.classList.remove('explorer-resizing');sizing();sync()};grip.onpointerup=stop;grip.onpointercancel=stop;grip.onlostpointercapture=stop;
 window.addEventListener('storage',e=>{if(e.key==='creative-interface')sizing()});window.addEventListener('creative-appearance-sizing',sizing);window.addEventListener('resize',sizing);sizing();
 window.whiteboardWorkspace={toggle,explorer,sync};
})();
