const fs=require('fs'),os=require('os'),path=require('path'),net=require('net'),{spawn}=require('child_process'),assert=require('assert');
const {chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'whiteboard-cells-'));const port=await require('./browser-port.cjs')();const base='http://127.0.0.1:'+port,proc=spawn(process.env.PYTHON||'python',[root+'/server.py'],{env:{...process.env,CREATIVE_BOARD_PORT:String(port),CREATIVE_BOARD_DATA_DIR:tmp,PYTHONIOENCODING:'utf-8'},windowsHide:true});let browser;try{
for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/index.html');await p.waitForFunction(()=>board&&!loading&&typeof cellItemGrid==='function');
await p.evaluate(()=>{board.nodes=[{id:'n',type:'note',title:'声音记录',body:'留意开头的短促声。',x:40,y:100,w:300,h:220,tags:[]},{id:'t',type:'table',title:'镜头表',columns:['画面','声音'],rows:[['',''],['下一镜','']],x:450,y:100,w:780,h:500,tags:[]}];board.edges=[];board.view={x:0,y:0,z:1};selected=new Set(['n']);render();canvas.focus();change()});
await p.keyboard.press('Control+c');await p.evaluate(()=>openEditor('t'));await p.locator('[data-row="0"][data-col="0"]').click();await p.keyboard.press('Control+v');await p.waitForFunction(()=>board.nodes.find(n=>n.id==='t').cellItems?.[0]?.[0]?.length===1);assert.equal(await p.locator('[data-cell="0,0"] [data-cell-note-field="body"]').inputValue(),'留意开头的短促声。');await p.locator('[data-cell="0,0"] [data-cell-note-field="body"]').fill('这里改的是单元格里的副本。');assert.equal(await p.evaluate(()=>board.nodes.find(n=>n.id==='n').body),'留意开头的短促声。');
// Upload a tiny valid PCM WAV and drag it from the same library payload used by the UI.
const wav=Buffer.alloc(44+1600);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(1600,40);const response=await fetch(base+'/api/assets/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':'tap.wav'},body:wav});assert(response.ok);const audio=await response.json();await p.evaluate(()=>loadAssets());const dt=await p.evaluateHandle(id=>{const d=new DataTransfer();d.setData('application/x-creative-assets',JSON.stringify([id]));return d},audio.id);await p.locator('[data-cell="0,1"]').dispatchEvent('drop',{dataTransfer:dt});await p.waitForFunction(()=>!!document.querySelector('[data-cell="0,1"] audio'));await p.locator('[data-cell="0,1"] audio').evaluate(async el=>{await el.play();el.pause()});
await p.evaluate(()=>{const n=board.nodes.find(n=>n.id==='t');moveTable(n,'row',0,1);moveTable(n,'column',0,1)});assert.equal(await p.evaluate(()=>board.nodes.find(n=>n.id==='t').cellItems[1][1][0].body),'这里改的是单元格里的副本。');assert.equal(await p.locator('[data-cell="1,0"] audio').count(),1);await p.evaluate(()=>persist());await p.reload();await p.waitForFunction(()=>board&&!loading);assert.equal(await p.locator('.read-layout [data-cell="1,0"] audio').count(),1);await p.waitForTimeout(150);assert(await p.locator('.read-layout [data-cell="1,0"] > textarea').isHidden());assert(await p.locator('.read-layout [data-cell="1,0"] [data-cell-note-field="body"]').isHidden());const mediaHeight=await p.locator('.read-layout [data-cell="1,0"] .cell-content').evaluate(e=>e.getBoundingClientRect().height);assert(mediaHeight<145,'Audio should not reserve empty body space: '+mediaHeight);await p.evaluate(()=>showWorkspaceTab('manager'));if(process.env.CELLS_SCREENSHOT)await p.screenshot({path:process.env.CELLS_SCREENSHOT});await p.evaluate(()=>openEditor('t'));await p.locator('[data-cell="1,1"] .cell-content').hover();await p.locator('[data-cell="1,1"] [data-cell-extract]').click();assert.equal(await p.evaluate(()=>board.nodes.length),3);await p.evaluate(()=>openEditor('t'));await p.locator('[data-cell="1,1"] .cell-content').hover();await p.locator('[data-cell="1,1"] [data-cell-remove]').click();assert.equal(await p.evaluate(()=>board.nodes.find(n=>n.id==='t').cellItems[1][1].length),0);await p.evaluate(()=>undo());assert.equal(await p.evaluate(()=>board.nodes.find(n=>n.id==='t').cellItems[1][1].length),1);
console.log('单元格：便签复制粘贴、独立编辑、音频拖入播放、行列移动、保存重载、取出和撤销通过');
await p.evaluate(()=>{selected=new Set(['n']);openEditor('n')});await p.locator('#body').click();await p.keyboard.press('Control+End');for(let i=0;i<35;i++){await p.keyboard.insertText('这一行继续记录拍摄时观察到的细节。');await p.keyboard.press('Enter')}await p.waitForTimeout(100);assert(await p.locator('.live-layout .edit-scroll').evaluate(e=>e.scrollTop)>400);await p.keyboard.press('Control+Home');await p.waitForTimeout(100);assert(await p.locator('.live-layout .edit-scroll').evaluate(e=>e.scrollTop)<130);
await p.evaluate(()=>openEditor('t'));await p.locator('[data-row="1"][data-col="1"]').click();for(let i=0;i<40;i++){await p.keyboard.insertText('继续写分镜说明');await p.keyboard.press('Enter')}await p.waitForTimeout(100);assert(await p.locator('.live-layout .table-scroll').evaluate(e=>e.scrollTop)>400);await p.keyboard.press('Control+Home');await p.waitForTimeout(100);console.log('长文编辑：便签与表格跟随输入光标、返回开头通过');assert.deepEqual(errors,[]);
}finally{if(browser)await browser.close();proc.kill();await new Promise(r=>proc.once('exit',r));const resolved=path.resolve(tmp);assert(resolved.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(resolved,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
