const fs=require('fs'),os=require('os'),path=require('path'),net=require('net'),{spawn}=require('child_process'),assert=require('assert');
const {chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'whiteboard-tabs-'));const port=await require('./browser-port.cjs')();const base='http://127.0.0.1:'+port,proc=spawn(process.env.PYTHON||'python',[root+'/server.py'],{env:{...process.env,CREATIVE_BOARD_PORT:String(port),CREATIVE_BOARD_DATA_DIR:tmp,PYTHONIOENCODING:'utf-8'},windowsHide:true});let browser;try{
for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
for(const [id,name] of [['a','素材观察'],['b','镜头编排'],['c','待确认的问题']]){const value={format:'creative-board',version:1,name,folder:'',nodes:id==='a'?[{id:'note',type:'note',title:'纸面与光线',body:'移动角度后，折痕会更清楚。',tags:[],x:60,y:110,w:330,h:260}]:id==='c'?[{id:'question',type:'note',title:'需要补拍：侧光',body:'先比较两个角度，再决定用哪个镜头。',tags:[],x:110,y:130,w:320,h:240,color:'#dfead8'}]:[],edges:[],view:{x:0,y:0,z:1}};assert((await fetch(base+'/api/boards/'+id,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':'new'},body:JSON.stringify(value)})).ok)}
browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true});const ctx=await browser.newContext({viewport:{width:1560,height:980},permissions:['clipboard-read','clipboard-write']});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>model.tabs.length===1&&frames.values().next().value?.contentWindow.whiteboardPane?.state().boardId);
async function open(name,side='left'){await p.locator('.add-tab[data-side='+side+']').click();await p.locator('#boardChoices').getByRole('button',{name:new RegExp(name)}).click();await p.waitForFunction(name=>{const t=model.tabs.find(t=>t.name===name);return t&&frames.get(t.id)?.contentWindow.whiteboardPane?.state().boardId===t.boardId},name)}
await open('素材观察');const a=p.frames().find(f=>new URL(f.url()).searchParams.get('board')==='a');await a.waitForFunction(()=>board&&!loading);await a.evaluate(()=>window.tabMarker='preserved');await p.locator('#openBoards').click();await p.waitForFunction(()=>window.whiteboardWorkspace.explorer());const explorer=p.frames().find(f=>new URL(f.url()).searchParams.get('explorer')==='1');assert(await explorer.locator('#workspaceSidebar').isVisible());await explorer.locator('#assetsButton').click();assert(await explorer.locator('#assetPane').isVisible());await p.locator('#openBoards').click();assert(await p.locator('#globalExplorer').isHidden());assert(await a.locator('#workspaceSidebar').isHidden());assert.equal(await p.locator('#shellHeader nav [data-command=library]').count(),0);
await a.locator('[data-id=note]').click({position:{x:80,y:80}});await p.keyboard.press('Control+c');
await open('镜头编排');const b=p.frames().find(f=>new URL(f.url()).searchParams.get('board')==='b');await b.waitForFunction(()=>board&&!loading);await p.keyboard.press('Control+v');await b.waitForFunction(()=>board.nodes.length===1);assert.equal(await b.evaluate(()=>board.nodes[0].body),'移动角度后，折痕会更清楚。');
await p.getByRole('tab',{name:'素材观察',exact:true}).click();assert.equal(await a.evaluate(()=>window.tabMarker),'preserved');assert.equal(await a.evaluate(()=>selected.has('note')),true);await p.getByRole('tab',{name:'镜头编排',exact:true}).click();
await p.locator('#splitToggle').click();assert(await p.evaluate(()=>model.split));assert(await p.evaluate(()=>model.tabs.find(t=>t.boardId==='b').side==='right'));assert.equal(await p.locator('.board-frame:visible').count(),2);
const divider=await p.locator('#splitter').boundingBox();await p.mouse.move(divider.x+4,300);await p.mouse.down();await p.mouse.move(1050,300,{steps:8});await p.mouse.up();assert(Math.abs(await p.evaluate(()=>model.ratio)-1050/1560*100)<1);await p.locator('#splitter').dblclick({position:{x:4,y:200}});assert.equal(await p.evaluate(()=>model.ratio),50);await p.locator('#splitter').focus();await p.keyboard.press('ArrowLeft');assert.equal(await p.evaluate(()=>model.ratio),48);
console.log('标签切换保留现场、跨标签粘贴、双栏、拖动比例、复位和键盘调整通过');
await p.getByRole('tab',{name:'镜头编排',exact:true}).click({button:'right'});await p.getByRole('button',{name:'移到另一侧',exact:true}).click();assert.equal(await p.evaluate(()=>model.tabs.find(t=>t.boardId==='b').side),'left');assert.equal(await a.evaluate(()=>window.tabMarker),'preserved');
await open('待确认的问题','right');const c=p.frames().find(f=>new URL(f.url()).searchParams.get('board')==='c');await c.waitForFunction(()=>board&&!loading);await c.evaluate(()=>window.tabMarker='right');
await p.locator('#splitToggle').click();assert.equal(await p.locator('.board-frame:visible').count(),1);await p.locator('#splitToggle').click();assert.equal(await c.evaluate(()=>window.tabMarker),'right');
await p.locator('.tab').filter({has:p.getByRole('tab',{name:'镜头编排',exact:true})}).dragTo(p.locator('.tab').filter({has:p.getByRole('tab',{name:'素材观察',exact:true})}));assert.equal(await p.evaluate(()=>model.tabs.filter(t=>t.side==='left')[0].boardId),'b');assert.equal(await a.evaluate(()=>window.tabMarker),'preserved');
// Header commands go to the most recently used pane.
await p.getByRole('tab',{name:'素材观察',exact:true}).click();await p.locator('[data-command=ai]').click();await a.waitForFunction(()=>document.getElementById('aiTaskScope'));assert.equal(await c.locator('#aiTaskScope').count(),0);await a.getByRole('button',{name:'关闭',exact:true}).click();
await p.getByRole('tab',{name:'镜头编排',exact:true}).click();await b.evaluate(()=>persist());await b.evaluate(()=>fit());await c.evaluate(()=>fit());await p.waitForTimeout(4000);await p.screenshot({path:process.env.TABS_SCREENSHOT||path.join(tmp,'tabs.png')});
const layout=await p.evaluate(()=>({ids:model.tabs.map(t=>t.boardId),split:model.split,ratio:model.ratio}));await p.reload();await p.waitForFunction(()=>model.tabs.length===3&&['left','right'].every(side=>{const t=current(side);return !t||pane(t)?.state().boardId===t.boardId}));assert.deepEqual(await p.evaluate(()=>({ids:model.tabs.map(t=>t.boardId),split:model.split,ratio:model.ratio})),layout);
assert.equal(await p.locator('.board-frame').count(),2);await p.getByRole('tab',{name:'素材观察',exact:true}).click();await p.waitForFunction(()=>pane(current())?.state().boardId==='a');assert.equal(await p.locator('.board-frame').count(),3);console.log('恢复时只加载可见分栏，点击后台标签后正常加载通过');
console.log('跨栏移动不重载、合并再拆分、工具栏跟随当前栏、刷新恢复布局通过');
await p.getByRole('tab',{name:'镜头编排',exact:true}).click();const newB=p.frames().find(f=>new URL(f.url()).searchParams.get('board')==='b');const snapshot=await newB.evaluate(()=>({board:clone(board),etag}));snapshot.board.name='外部修改';assert((await fetch(base+'/api/boards/b',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':snapshot.etag},body:JSON.stringify(snapshot.board)})).ok);await newB.evaluate(()=>{board.nodes[0].body='我的未保存修改';change()});await p.getByRole('button',{name:'关闭标签：镜头编排',exact:true}).click();await newB.waitForFunction(()=>blocked);assert.equal(await p.getByRole('tab',{name:'镜头编排',exact:true}).count(),1);assert.equal(await newB.evaluate(()=>board.nodes[0].body),'我的未保存修改');
await p.getByRole('button',{name:'关闭标签：待确认的问题',exact:true}).click();await p.waitForFunction(()=>!model.tabs.some(t=>t.boardId==='c'));assert((await fetch(base+'/api/boards/c')).ok);console.log('关闭标签保留文件、保存冲突时阻止关闭并保留修改通过');assert.deepEqual(errors,[]);
}finally{if(browser)await browser.close();proc.kill();await new Promise(r=>proc.once('exit',r));const resolved=path.resolve(tmp);assert(resolved.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(resolved,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
